version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: weather_subscription_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  api:
    build: ./api
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
