version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: weather_subscription_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  api:
    build: ./api
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3005:80'
    depends_on:
      - api
    networks:
      - network

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '8080:80'
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
