#!/bin/bash
set -e

env

echo "NODE_ENV=${NODE_ENV}
API_PREFIX=${API_PREFIX}
SERVER_PORT=${SERVER_PORT}
SERVER_HOST=${SERVER_HOST}
WEATHER_API_KEY=${WEATHER_API_KEY}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_HOST=${POSTGRES_HOST}
NODEMAILER_USER=${NODEMAILER_USER}
NODEMAILER_PASS=${NODEMAILER_PASS}" > .env

echo ".env file created:"
cat .env

node dist/main